// src/App.tsx
import { useState } from "react";
import type { ChangeEvent, VFC } from "react";
import Label from "./Label";
import romanize from "./romanize";
import TextArea from "./TextArea";

const App: VFC = () => {
  const [source, setSource] = useState("");
  const [result, setResult] = useState("");

  function onSourceChange(event: ChangeEvent<HTMLTextAreaElement>) {
    setSource(event.target.value);
    setResult(romanize(event.target.value));
  }

  return (
    <>
      <div className="text-center">
        <Label htmlFor="hangeul">Korean Text</Label>
        <TextArea
          id="hangeul"
          value={source}
          autoFocus
          onChange={onSourceChange}
        />
      </div>
      <div className="text-center">
        <Label htmlFor="results">Results</Label>
        <TextArea id="results" value={result} readOnly tabIndex={-1} />
      </div>
    </>
  );
};

export default App;

// src/App.vue
<template>
  <div class="text-center">
    <FormLabel for="hangeul">Korean Text</FormLabel>
    <TextArea id="hangeul" v-model="source" autofocus />
  </div>
  <div class="text-center">
    <FormLabel for="results">Results</FormLabel>
    <TextArea id="results" v-model="result" readonly :tabindex="-1" />
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from "vue";
import FormLabel from "./components/FormLabel.vue";
import TextArea from "./components/TextArea.vue";
import romanize from "./romanize";

const source = ref("");
const result = computed(() => romanize(source.value));
</script>
